version: 2
jobs:
  init:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: git clone https://github.com/danmaq/danmaq.article.git
      - run: yarn run clean
      - run: yarn run production:init
      - run: yarn run production:origin
      - run: yarn run build --verbose
      - save_cache:
          paths:
          - public
          key: v1-pages
  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - restore_cache:
          keys:
          - v1-pages
      - run: git config --global user.name "Shuhei Nomura"
      - run: git config --global user.email "info@danmaq.com"
      - run: yarn run production:commit
      - run: yarn run production:push
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - init
      - build:
          requires:
            - init
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
