version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          TMPDIR: /tmp
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: git clone https://github.com/danmaq/danmaq.article.git
      - run: git config --global user.name "Shuhei Nomura"
      - run: git config --global user.email "info@danmaq.com"
      # - run: yarn run staging:build --verbose
      # - run: yarn run staging:commit
      - run: yarn run production:clean
      - run: yarn run production:clone
      - run: yarn run production:truncate
      - run: node --max_old_space_size=1792 --stack_size=1280 ./node_modules/.bin/gatsby build --verbose
